### ISSUE TITLE
Wrong Weekdays

### ISSUE THREAD

**Issue by PhilippLeh** [onesine/react-tailwindcss-datepicker#150] opened 2023-06-13 10:10 UTC
The Datepicker shows the wrong weekday, or do I miss something? 

<img width="324" alt="image" src="https://github.com/onesine/react-tailwindcss-datepicker/assets/61593457/7d8bd864-cf11-4f40-aa1b-1c752da04031">

**Comment by onesine** [comment] 2023-06-13 15:24
Hi 👋  @PhilippLeh 

Thank you for your feedback.

Can you show us your code so that we can reproduce this problem.

**Comment by PhilippLeh** [comment] 2023-06-13 15:43
**Implementation**
```
import {NextPageWithLayout} from "../common/types/Page";
import Head from "next/head";
import React, {useState} from "react";
import Datepicker from "react-tailwindcss-datepicker";

const Test: NextPageWithLayout = () => {

    const [date, setDate] = useState({startDate: null, endDate: null})

    // @ts-ignore
    const handleChange = (newDate) => {
        setDate!({startDate: newDate.startDate, endDate: newDate.endDate});
    };

    return (
        <div className="w-1/4">
            <Datepicker
                // @ts-ignore
                value={date}
                label="Datumsbereich"
                onChange={handleChange}
                useRange={true}
                showFooter={true}
                showShortcuts={true}
                asSingle={false}
                configs={{
                    shortcuts: {
                        today: "Heute",
                        yesterday: "Gestern",
                        past: period => `Letzten ${period}-Tage`,
                        currentMonth: "Dieser Monat",
                        pastMonth: "Letztes Monat",
                        thisYear: {
                            text: "Dieses Jahr",
                            period: {
                                // @ts-ignore
                                start: new Date(new Date().getFullYear(), 0, 1),
                                // @ts-ignore
                                end: new Date()
                            }
                        }
                    },
                }}
                separator="-"
                displayFormat="DD.MM.YYYY"
                startWeekOn="mon"
                language="de-at"
            />
        </div>
    )
}

Test.getLayout = (page: any) => {
    return (
        <>
            <Head>
                <title>
                    Test
                </title>
            </Head>
            {page}
        </>
    )
}

export default Test
```


**Result**
<img width="756" alt="image" src="https://github.com/onesine/react-tailwindcss-datepicker/assets/61593457/bbdc050d-7bc2-4679-b9aa-4b7f17679cd3">

**Comment by onesine** [comment] 2023-06-13 18:53
I have just published a new version. Can you try it and close this exit if it's ok.

**Comment by PhilippLeh** [comment] 2023-06-14 05:50
@onesine I'm sorry, but that didn't change anything.

**Comment by PhilippLeh** [comment] 2023-06-14 06:54
I just pulled the repo and replaced the usage in my code, to debug this issue and thats what I found: 

To get the full name of the first day in the month I had to change the format to: 
dddd (Displays the day as a full name, Sunday-Saturday) because ddd (Displays the day as an abbreviation, Sun-Sat)

Furthermore dayjs returned the weekdays already in the right language (in my case german), so I also had to translate the getNumberOfDay mapping like so:

```
["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"].forEach(
        (item, index) => {
            if (item.includes(dayString)) {
                number = (index + startDateModifier) % 7;
            }
        }
    );

```

I have not figured out yet why this happens, but it now works for me. Maybe its because of some dayjs config/usage outside the datepicker.

**Closed** 2023-06-14 07:16 UTC

**Comment by onesine** [comment] 2023-06-14 20:30
I'm sorry I couldn't find a solution for you. This is a very peculiar situation. I'm going to keep looking into the problem, though.

**Comment by PhilippLeh** [comment] 2023-06-16 10:17
No worries, thanks a lot for your effort!

**Comment by cheeselemon** [comment] 2023-12-07 09:13
I, too, encountered this bug, and found the reason for this after thoroughly looking at the codebase.

Apparently if you declare dayjs.locale() somewhere alongside using this library, 
the weekday matching function below will fail:
https://github.com/onesine/react-tailwindcss-datepicker/blob/bf063fe6458787622ca500ec9a33d9b2feb955d1/src/helpers/index.ts#L174

because the date argument provided using `getFirstDayInMonth(date).ddd`
will return what was defined through dayjs.locale() other than "en" will return non english weekday string,
thus won't match anything so the variable `number` will always be zero. 

I'm implementing a fix, and will update with a pull request.

**Comment by onesine** [comment] 2024-08-13 11:01
Hello @cheeselemon.
Sorry for the late reply.
Thanks for the contribution.
